trigger:
  - main

container:
  image: aquasec/aqua-scanner
  env:
    AQUA_KEY: $(AQUA_KEY)
    AQUA_SECRET: $(AQUA_SECRET)
    TRIVY_RUN_AS_PLUGIN: aqua\
    #AQUA_ASSURANCE_EXPORT: /tmp/scanresults.json
    # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)

steps:
- script: |
    trivy fs --scanners misconfig,vuln,secret .
    # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    # To enable SAST scanning, add: --sast
#- script: cat /tmp/scanresults.json | jq